"""Mail events for new changes only. No messages are generated by migrations."""
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver

from .email_queue import enqueue
from .email_service import portal_url
from .models import Advertiser, Business, Invoice


def enabled():
    return getattr(settings, 'GCA_EMAIL_EVENTS_ENABLED', False)


@receiver(pre_save, sender=get_user_model())
@receiver(pre_save, sender=Business)
@receiver(pre_save, sender=Invoice)
def remember_previous(sender, instance, raw=False, **kwargs):
    if raw or not enabled():
        return
    fields = ['password', 'email'] if sender == get_user_model() else ['status']
    instance._email_previous = sender.objects.filter(pk=instance.pk).values(*fields).first() if instance.pk else None


@receiver(post_save, sender=Advertiser)
def welcome_advertiser(sender, instance, raw=False, **kwargs):
    if raw or not enabled() or instance.status != 'active' or not instance.user_id:
        return
    user = instance.user
    if not user.is_active or user.is_staff:
        return
    enqueue('welcome', user.email, 'Bem-vindo ao Guia!', [
        f'Olá, {instance.contact_name or instance.name}! Sua conta de anunciante está disponível.',
        'Acesse sua área para acompanhar seus estabelecimentos, anúncios e informações financeiras.',
        'Se ainda não definiu sua senha, use “Esqueci minha senha” na tela de entrada. Nunca enviamos senhas por e-mail.',
    ], url=portal_url('/anunciante/login'), key=f'welcome:{instance.pk}:{user.pk}',
        guard={'model': 'Advertiser', 'filters': {'pk': instance.pk, 'status': 'active',
            'user_id': user.pk, 'user__email': user.email, 'user__is_active': True}})


@receiver(post_save, sender=get_user_model())
def account_security(sender, instance, raw=False, **kwargs):
    if raw or not enabled() or instance.is_staff:
        return
    previous = getattr(instance, '_email_previous', None)
    if not previous:
        return
    if previous['password'] != instance.password:
        enqueue('password_changed', instance.email, 'Sua senha foi alterada', [
            'A senha da sua conta foi alterada.',
            'Se você não reconhece essa alteração, solicite uma nova senha na tela de entrada e entre em contato com o atendimento.',
        ], url=portal_url('/anunciante/login'))
    if previous['email'].casefold() != instance.email.casefold():
        for address in set([previous['email'], instance.email]):
            enqueue('email_changed', address, 'E-mail da conta atualizado', [
                'O endereço de e-mail associado à sua conta foi alterado.',
                'Se não reconhece essa alteração, entre em contato com o atendimento do Guia.',
            ], url=portal_url('/anunciante/login'))


@receiver(post_save, sender=Business)
def business_status(sender, instance, created, raw=False, **kwargs):
    if raw or not enabled():
        return
    previous = getattr(instance, '_email_previous', None)
    if not created and (not previous or previous['status'] == instance.status):
        return
    messages = {
        'pending': ('Cadastro recebido', 'Recebemos seu cadastro. Ele aguarda análise antes da publicação.'),
        'active': ('Cadastro aprovado', 'Seu estabelecimento foi aprovado. A exibição pública também depende das regras e datas dos anúncios.'),
        'suspended': ('Publicação suspensa', 'A publicação do seu estabelecimento foi suspensa. Consulte o atendimento para esclarecer o motivo.'),
        'inactive': ('Cadastro desativado', 'Seu estabelecimento foi desativado no Guia.'),
    }
    if instance.status not in messages:
        return
    title, text = messages[instance.status]
    recipients = set(instance.advertisers.filter(status='active').values_list('email', flat=True))
    if instance.email:
        recipients.add(instance.email)
    for recipient in recipients:
        enqueue('business_' + instance.status, recipient, title, [f'Estabelecimento: {instance.name}', text], url=portal_url(),
            guard={'model': 'Business', 'filters': {'pk': instance.pk, 'status': instance.status}})


@receiver(post_save, sender=Invoice)
def invoice_status(sender, instance, created, raw=False, **kwargs):
    if raw or not enabled():
        return
    previous = getattr(instance, '_email_previous', None)
    if not created and (not previous or previous['status'] == instance.status):
        return
    title = {'open': 'Nova fatura disponível', 'paid': 'Pagamento registrado',
        'overdue': 'Fatura em atraso', 'cancelled': 'Fatura cancelada'}.get(instance.status)
    if not title:
        return
    advertiser = instance.subscription.advertiser
    recipient = advertiser.billing_email or advertiser.email
    enqueue('invoice_' + instance.status, recipient, title, [
        f'Fatura #{instance.pk} — {instance.subscription.business.name}',
        f'Valor: R$ {instance.total:.2f}. Vencimento: {instance.due_date:%d/%m/%Y}.',
        'Consulte os detalhes na área financeira. Esta mensagem não contém boleto nem realiza débito automático.',
    ], url=portal_url('/area-do-anunciante/financeiro'),
        guard={'model': 'Invoice', 'filters': {'pk': instance.pk, 'status': instance.status,
            'due_date': instance.due_date.isoformat(), 'amount': str(instance.amount),
            'discount': str(instance.discount), 'late_fee': str(instance.late_fee)}})
