location /api/ {
    proxy_ssl_server_name on;
    proxy_set_header Host webapp415078.ip-45-79-2-160.cloudezapp.io;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass https://webapp415078.ip-45-79-2-160.cloudezapp.io;
}
