# Generated by Django 5.2.13 on 2026-07-07 00:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='slug')),
                ('icon', models.CharField(blank=True, max_length=80, verbose_name='icone')),
                ('color', models.CharField(blank=True, max_length=120, verbose_name='cor')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='titulo')),
                ('schedule_text', models.CharField(blank=True, max_length=160, verbose_name='data/horario exibido')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='inicio')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='fim')),
                ('location', models.CharField(max_length=180, verbose_name='local')),
                ('description', models.TextField(verbose_name='descricao')),
                ('image_url', models.URLField(blank=True, verbose_name='imagem')),
                ('is_published', models.BooleanField(default=True, verbose_name='publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['starts_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UsefulNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('phone', models.CharField(max_length=30, verbose_name='telefone')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
                ('category', models.CharField(choices=[('emergency', 'Emergencia'), ('service', 'Servico')], max_length=20, verbose_name='categoria')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'telefone util',
                'verbose_name_plural': 'telefones uteis',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nome do estabelecimento')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
                ('street', models.CharField(max_length=180, verbose_name='rua')),
                ('number', models.CharField(max_length=20, verbose_name='numero')),
                ('complement', models.CharField(blank=True, max_length=120, verbose_name='complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=120, verbose_name='bairro')),
                ('city', models.CharField(default='Araraquara', max_length=100, verbose_name='cidade')),
                ('state', models.CharField(default='SP', max_length=2, verbose_name='UF')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('phone_whatsapp', models.CharField(max_length=30, verbose_name='fone/whatsapp')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('website', models.URLField(blank=True, verbose_name='site')),
                ('instagram', models.CharField(blank=True, max_length=80, verbose_name='instagram')),
                ('image_url', models.URLField(blank=True, verbose_name='imagem')),
                ('opening_hours', models.CharField(blank=True, max_length=180, verbose_name='horario de funcionamento')),
                ('is_featured', models.BooleanField(default=False, verbose_name='destaque')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('pending', 'Pendente'), ('active', 'Publicado'), ('inactive', 'Inativo')], default='pending', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publicado em')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='core.category', verbose_name='categoria')),
                ('tags', models.ManyToManyField(blank=True, related_name='businesses', to='core.tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'estabelecimento',
                'verbose_name_plural': 'estabelecimentos',
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='titulo')),
                ('discount_code', models.CharField(max_length=40, verbose_name='codigo do cupom')),
                ('description', models.TextField(verbose_name='descricao')),
                ('starts_at', models.DateField(blank=True, null=True, verbose_name='inicio')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='validade')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='core.business', verbose_name='estabelecimento')),
            ],
            options={
                'verbose_name': 'cupom',
                'verbose_name_plural': 'cupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=120, verbose_name='nome do avaliador')),
                ('author_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail do avaliador')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='nota')),
                ('comment', models.TextField(verbose_name='comentario')),
                ('is_approved', models.BooleanField(default=False, verbose_name='aprovado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.business', verbose_name='estabelecimento')),
            ],
            options={
                'verbose_name': 'avaliacao',
                'verbose_name_plural': 'avaliacoes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['status', 'is_featured'], name='core_busine_status_5c6ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['city', 'neighborhood'], name='core_busine_city_cbf272_idx'),
        ),
    ]
