# Generated by Django 5.2.13 on 2026-07-07 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='logo_image',
            field=models.TextField(blank=True, verbose_name='logomarca'),
        ),
        migrations.AlterField(
            model_name='business',
            name='image_url',
            field=models.TextField(blank=True, verbose_name='imagem de capa'),
        ),
        migrations.CreateModel(
            name='BusinessImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(verbose_name='imagem')),
                ('alt_text', models.CharField(blank=True, max_length=160, verbose_name='texto alternativo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.business', verbose_name='estabelecimento')),
            ],
            options={
                'verbose_name': 'imagem do estabelecimento',
                'verbose_name_plural': 'imagens do estabelecimento',
                'ordering': ['order', 'id'],
            },
        ),
    ]
