# Generated by Django 5.2.15 on 2026-07-29 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_create_backoffice_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('annual', 'Anual')], default='monthly', max_length=20, verbose_name='ciclo')),
                ('max_ads', models.PositiveSmallIntegerField(default=1, verbose_name='limite de anuncios')),
                ('featured', models.BooleanField(default=False, verbose_name='inclui destaque')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'plano de publicidade',
                'verbose_name_plural': 'planos de publicidade',
                'ordering': ('price', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='nome/razao social')),
                ('document', models.CharField(blank=True, max_length=24, verbose_name='CPF/CNPJ')),
                ('contact_name', models.CharField(blank=True, max_length=140, verbose_name='responsavel')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefone/WhatsApp')),
                ('billing_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail financeiro')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('prospect', 'Prospect')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('businesses', models.ManyToManyField(blank=True, related_name='advertisers', to='core.business', verbose_name='anuncios')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertiser_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario de acesso')),
            ],
            options={
                'verbose_name': 'anunciante',
                'verbose_name_plural': 'anunciantes',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AdvertisingSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='termino')),
                ('next_due_date', models.DateField(verbose_name='proximo vencimento')),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor contratado')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('pending', 'Pendente'), ('suspended', 'Suspensa'), ('cancelled', 'Cancelada'), ('expired', 'Vencida')], default='active', max_length=20)),
                ('auto_renew', models.BooleanField(default=True, verbose_name='renovacao automatica')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.advertiser')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.business', verbose_name='anuncio')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.advertisingplan')),
            ],
            options={
                'verbose_name': 'assinatura de anuncio',
                'verbose_name_plural': 'assinaturas de anuncios',
                'ordering': ('next_due_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=180, verbose_name='descricao')),
                ('reference_month', models.DateField(verbose_name='competencia')),
                ('due_date', models.DateField(verbose_name='vencimento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='desconto')),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='multa/juros')),
                ('status', models.CharField(choices=[('open', 'Em aberto'), ('paid', 'Paga'), ('overdue', 'Vencida'), ('cancelled', 'Cancelada')], default='open', max_length=20)),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='pago em')),
                ('payment_method', models.CharField(blank=True, choices=[('pix', 'PIX'), ('boleto', 'Boleto'), ('card', 'Cartao'), ('transfer', 'Transferencia'), ('cash', 'Dinheiro'), ('other', 'Outro')], max_length=20, verbose_name='forma de pagamento')),
                ('external_reference', models.CharField(blank=True, max_length=120, verbose_name='referencia externa')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.advertisingsubscription')),
            ],
            options={
                'verbose_name': 'cobranca',
                'verbose_name_plural': 'cobrancas',
                'ordering': ('due_date', '-created_at'),
            },
        ),
    ]
