# Generated by Django 5.2.15 on 2026-07-29 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_advertisingplan_advertiser_advertisingsubscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='titulo')),
                ('short_description', models.CharField(blank=True, max_length=240, verbose_name='chamada curta')),
                ('description', models.TextField(blank=True, verbose_name='texto do anuncio')),
                ('call_to_action', models.CharField(blank=True, max_length=80, verbose_name='chamada para acao')),
                ('destination_url', models.URLField(blank=True, verbose_name='link de destino')),
                ('logo_image', models.TextField(blank=True, verbose_name='logomarca')),
                ('cover_image', models.TextField(blank=True, verbose_name='imagem de capa')),
                ('video_url', models.URLField(blank=True, verbose_name='video')),
                ('starts_at', models.DateField(blank=True, null=True, verbose_name='inicio da publicacao')),
                ('ends_at', models.DateField(blank=True, null=True, verbose_name='fim da publicacao')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('review', 'Em revisao'), ('published', 'Publicado'), ('paused', 'Pausado'), ('ended', 'Encerrado')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False, verbose_name='destaque')),
                ('is_primary', models.BooleanField(default=True, verbose_name='anuncio principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='core.business', verbose_name='estabelecimento')),
                ('tags', models.ManyToManyField(blank=True, related_name='advertisements', to='core.tag')),
            ],
            options={
                'verbose_name': 'anuncio',
                'verbose_name_plural': 'anuncios',
                'ordering': ('-is_primary', '-updated_at'),
            },
        ),
        migrations.AddField(
            model_name='advertisingsubscription',
            name='advertisement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.advertisement', verbose_name='campanha/anuncio'),
        ),
        migrations.CreateModel(
            name='AdvertisementMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Imagem'), ('video', 'Video')], default='image', max_length=10)),
                ('file_data', models.TextField(verbose_name='arquivo/URL')),
                ('alt_text', models.CharField(blank=True, max_length=180, verbose_name='texto alternativo')),
                ('caption', models.CharField(blank=True, max_length=240, verbose_name='legenda')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='core.advertisement')),
            ],
            options={
                'verbose_name': 'midia do anuncio',
                'verbose_name_plural': 'midias do anuncio',
                'ordering': ('order', 'id'),
            },
        ),
    ]
