# Generated by Django 5.2.15 on 2026-07-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_migrate_business_content_to_advertisements'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='advertisement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('business',), name='one_primary_advertisement_per_business'),
        ),
    ]
