# Generated by Django 5.2.15 on 2026-07-29 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_advertisement_one_primary_advertisement_per_business'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackofficeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('registration', 'Novo cadastro'), ('advertisement', 'Anuncio'), ('review', 'Avaliacao'), ('finance', 'Financeiro'), ('system', 'Sistema')], default='system', max_length=24)),
                ('title', models.CharField(max_length=160)),
                ('message', models.CharField(max_length=320)),
                ('url', models.CharField(blank=True, default='/backoffice', max_length=240)),
                ('unique_key', models.CharField(max_length=180, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_backoffice_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backoffice_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notificacao do backoffice',
                'verbose_name_plural': 'notificacoes do backoffice',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.TextField()),
                ('auth', models.TextField()),
                ('user_agent', models.CharField(blank=True, max_length=320)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'inscricao push',
                'verbose_name_plural': 'inscricoes push',
            },
        ),
    ]
