# Generated by Django 5.2.15 on 2026-09-10 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_business_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('event', models.CharField(max_length=24)),
                ('count', models.PositiveIntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='core.business')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('business', 'day', 'event'), name='unique_business_daily_metric')],
            },
        ),
    ]
