# Generated by Django 5.2.15 on 2026-09-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_businessdailymetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisingsubscription',
            name='billing_anchor_day',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='recurrence_key',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
    ]
