# Generated by Django 5.2.15 on 2026-09-23 04:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_advertisement_published_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionalEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=180, unique=True)),
                ('kind', models.CharField(max_length=40)),
                ('recipient', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=180)),
                ('paragraphs', models.JSONField(default=list)),
                ('guard', models.JSONField(blank=True, default=dict)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sending', 'Em envio'), ('sent', 'Aceito pelo servidor de e-mail'), ('failed', 'Falhou'), ('expired', 'Expirado')], default='pending', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'e-mail transacional',
                'verbose_name_plural': 'e-mails transacionais',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'available_at'], name='email_pending_idx')],
            },
        ),
    ]
